<a href="https://colab.research.google.com/github/sergope/03MAIR-Algoritmos-de-Optimizacion/blob/master/Sergio_G%C3%B3mez_Seminario.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problema 1. 
### Organizar sesiones de doblaje <br>
• Se precisa coordinar el doblaje de una película.  <br>
• Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas.  <br>
• Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. <br>
• No es posible grabar más de 6 tomas por día. <br>
• El objetivo es planificar las sesiones por día de manera que se gasto
por los servicios de los actores de doblaje sea el menor posible <br> <br>


Número de actores: 10 <br>
Número de tomas : 30 <br>
Actores/Tomas : https://bit.ly/36D8IuK <br>

1 indica que el actor participa en la toma <br>
0 en caso contrario <br>


In [0]:
import numpy as np
import pprint

In [169]:
data = np.array([[1,1,1,1,1,0,0,0,0,0],[0,0,1,1,1,0,0,0,0,0],[0,1,0,0,1,0,1,0,0,0],[1,1,0,0,0,0,1,1,0,0],[0,1,0,1,0,0,0,1,0,0],[1,1,0,1,1,0,0,0,0,0],
[1,1,0,1,1,0,0,0,0,0],[1,1,0,0,0,1,0,0,0,0],[1,1,0,1,0,0,0,0,0,0],[1,1,0,0,0,1,0,0,1,0],[1,1,1,0,1,0,0,1,0,0],[1,1,1,1,0,1,0,0,0,0],
[1,0,0,1,1,0,0,0,0,0],[1,0,1,0,0,1,0,0,0,0],[1,1,0,0,0,0,1,0,0,0],[0,0,0,1,0,0,0,0,0,1],[1,0,1,0,0,0,0,0,0,0],[0,0,1,0,0,1,0,0,0,0],
[1,0,1,0,0,0,0,0,0,0],[1,0,1,1,1,0,0,0,0,0],[0,0,0,0,0,1,0,1,0,0],[1,1,1,1,0,0,0,0,0,0],[1,0,1,0,0,0,0,0,0,0],[0,0,1,0,0,1,0,0,0,0],
[1,1,0,1,0,0,0,0,0,1],[1,0,1,0,1,0,0,0,1,0],[0,0,0,1,1,0,0,0,0,0],[1,0,0,1,0,0,0,0,0,0],[1,0,0,0,1,1,0,0,0,0],[1,0,0,1,0,0,0,0,0,0]])

data


array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 0,

In [176]:
numero_actores = data.shape[1]
numero_tomas = data.shape[0]
max_tomas_por_dia = 6

print(numero_actores)
print(numero_tomas)



10
30


In [178]:
# Solución básica
def calcula_coste(matriz_solucion):
  matriz_coste = np.zeros(10, dtype=int)
  for dia in matriz_solucion:
    for act in range(len(sol)):
      if dia[act] > 0:
        matriz_coste[act] += 1
  return np.sum(matriz_coste)

def calcula_solucion(tomas, maximo_tomas):
  matriz_solucion = [np.zeros(10, dtype=int)]
  dia = 0
  n_tomas = 0

  for toma in tomas:
    if (n_tomas >= maximo_tomas):
      n_tomas = 0
      dia += 1
      matriz_solucion = np.append(matriz_solucion, [np.zeros(10, dtype=int)], axis=0)

    matriz_solucion[dia] = np.add(matriz_solucion[dia], toma)
    n_tomas +=1

  coste = calcula_coste(matriz_solucion)

  return coste, matriz_solucion


solucion = calcula_solucion(data, max_tomas_por_dia)
print('coste: ', solucion[0])
print('solucion: \n', solucion[1])


coste:  38
solucion: 
 [[3 5 2 4 4 0 2 2 0 0]
 [6 6 2 3 2 3 0 1 1 0]
 [4 1 3 2 1 2 1 0 0 1]
 [4 1 5 2 1 2 0 1 0 0]
 [5 1 1 4 3 1 0 0 1 1]]


In [181]:
mejor_coste = 9999999
intentos = 10000000

copia_data = np.copy(data)

for intento in range(intentos):
  solucion = calcula_solucion(copia_data, max_tomas_por_dia)
  if (solucion[0] < mejor_coste):
    mejor_coste = solucion[0]
    print(mejor_coste)
    mejor_matriz_solucion = solucion[1]
  
  random = np.random.randint(low=0, high=29, size=2)
  t = np.copy(copia_data[random[0]])
  copia_data[random[0]] = copia_data[random[1]]
  copia_data[random[1]] = t


print('coste: ', mejor_coste)
print('solucion: \n', mejor_matriz_solucion)

38
37
36
35
34
33
32
31
30
coste:  30
solucion: 
 [[2 4 0 3 3 2 1 2 0 0]
 [6 4 2 0 3 2 2 2 2 0]
 [4 0 6 0 0 3 0 0 0 0]
 [5 4 2 6 1 1 0 0 0 2]
 [5 2 3 6 4 0 0 0 0 0]]


In [0]:

data = np.array([[1,1,1,1],
[0,0,1,1],
[0,1,0,0],
[1,1,0,0],
[0,1,0,1],
[1,1,0,1],
[1,1,0,1],
[1,1,0,0]])

copia = np.copy(data)

print(np.random.randint(low=0, high=29, size=2))

numero_actores = data.shape[1]
numero_tomas = data.shape[0]

print(numero_actores)
print(numero_tomas)

copia