<a href="https://colab.research.google.com/github/sergope/03MAIR-Algoritmos-de-Optimizacion/blob/master/Sergio_G%C3%B3mez_Seminario.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sergio Gómez Pérez <br>
Seminario Algoritmos de optimización, problema 1 <br>
URL: https://colab.research.google.com/drive/1BfBitqted8DCyfFL9SpDPhsCa4MdjHYk <br>


## Problema 1. 
### Organizar sesiones de doblaje <br>
• Se precisa coordinar el doblaje de una película.  <br>
• Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas.  <br>
• Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. <br>
• No es posible grabar más de 6 tomas por día. <br>
• El objetivo es planificar las sesiones por día de manera que se gasto
por los servicios de los actores de doblaje sea el menor posible <br> <br>


Número de actores: 10 <br>
Número de tomas : 30 <br>
Actores/Tomas : https://bit.ly/36D8IuK <br>

1 indica que el actor participa en la toma <br>
0 en caso contrario <br>


Debemos tener en cuenta que nos encontramos frente a una variante del problema del viajero y por lo tanto un problema NP. De forma que no disponemos de una ecuación que nos permita llegar a una solución genérica. <br>

La única forma que tenemos de asegurarnos de que hemos obtenido la solución óptima es recorrer todas las posibilidades, es decir, crear un algoritmo que resuelva el problema por fuerza bruta. Esto no es una tarea sencilla ya que se trata de un problema con **complejidad factorial** cuyo número de posibles soluciones es el siguiente: <br>
 ### 30! = 2.65 * 10^32

(Sin tener en cuenta las restricciones)



## Solución al problema

Antes de empezar a programar nada debemos tener claro cuál es nuestro objetivo. En este caso necesitamos cuadrar los horarios de los actores para conseguir rodar un total de 30 tomas con el menor coste posible.

El coste vendrá indicado por la cantidad de días que trabaje cada actor, y debemos tener en cuenta la restricción de que no es posible rodar más de 6 tomás en un díay que todos los actores deben estar juntos al rodar una misma toma.

Para ello nuestro objetivo va a ser obtener como resultado una matriz Nx10, donde N es el número de días de rodaje y 10 el número de actores. Además cada casilla de la matriz indicará la cantidad de escenas que un actor ha rodado ese día.

Una vez conseguida esta matriz solución el cálculo del coste es muy sencillo. Lo único que debemos hacer es recorrer todas las celdas de esta matriz y sumar 1 al coste cuando el actor haya rodado 1 o más escenas (solo sumamos 1 ya que los actores cobran por día y no por toma). Por ejemplo, una matriz solución podría ser la siguiente: 
<br>

  **día 1: [3 5 2 4 4 0 2 2 0 0]** <br>
  **día 2: [6 6 2 3 2 3 0 1 1 0]** <br>
  **día 3: [4 1 3 2 1 2 1 0 0 1]** <br>
  **día 4: [4 1 5 2 1 2 0 1 0 0]** <br>
  **día 5: [5 1 1 4 3 1 0 0 1 1]** <br>


Como se puede apreciar en esta solución la cantídad de días de doblaje son 5, y si sumamos cuantos días ha tenido que rodar cada actor obtendremos el coste total. <br>
En este caso el **coste total** es de: **38**


### Solución óptima

A continuación vamos a calcular cuál sería el mínimo coste que podríamos obtener únicamente teniendo en cuenta el nº de escenas de cada actor y la limitación de 6 escenas por día. Para ello basta con calcular el mínimo coste para cada actor y sumarlo al final.
Por ejemplo, el primer actor tiene un total de 22 tomas. Como puede no rodar más de 6 por día tenemos que: <br>
22 / 6 = 3.66 -> redondeando sacamos que necesita un mínimo de 4 días, es decir, coste = 4

El segundo actor tiene un total de 14 tomas por lo que:
14 / 6 = 2.33 -> necesita un mínimo de 3 días. Coste = 3

Si repetimos este proceso para los 10 actores obtenemos que el **coste mínimo teórico es de 21**, sin embargo es posible que nunca podamos obtener este coste ya que no estamos teniendo en cuenta la restricción de que todos los actores de una misma toma deben rodar juntos el mismo día. <br>
Sabiendo estas características del problema ya estamos en condiciones de poder abordarlo.

### En primer lugar vamos a inicializar los datos del problema


In [34]:
import numpy as np

data = np.array([[1,1,1,1,1,0,0,0,0,0],[0,0,1,1,1,0,0,0,0,0],[0,1,0,0,1,0,1,0,0,0],[1,1,0,0,0,0,1,1,0,0],[0,1,0,1,0,0,0,1,0,0],[1,1,0,1,1,0,0,0,0,0],
[1,1,0,1,1,0,0,0,0,0],[1,1,0,0,0,1,0,0,0,0],[1,1,0,1,0,0,0,0,0,0],[1,1,0,0,0,1,0,0,1,0],[1,1,1,0,1,0,0,1,0,0],[1,1,1,1,0,1,0,0,0,0],
[1,0,0,1,1,0,0,0,0,0],[1,0,1,0,0,1,0,0,0,0],[1,1,0,0,0,0,1,0,0,0],[0,0,0,1,0,0,0,0,0,1],[1,0,1,0,0,0,0,0,0,0],[0,0,1,0,0,1,0,0,0,0],
[1,0,1,0,0,0,0,0,0,0],[1,0,1,1,1,0,0,0,0,0],[0,0,0,0,0,1,0,1,0,0],[1,1,1,1,0,0,0,0,0,0],[1,0,1,0,0,0,0,0,0,0],[0,0,1,0,0,1,0,0,0,0],
[1,1,0,1,0,0,0,0,0,1],[1,0,1,0,1,0,0,0,1,0],[0,0,0,1,1,0,0,0,0,0],[1,0,0,1,0,0,0,0,0,0],[1,0,0,0,1,1,0,0,0,0],[1,0,0,1,0,0,0,0,0,0]])

numero_actores = data.shape[1]
numero_tomas = data.shape[0]
max_tomas_por_dia = 6
mejor_coste = 99999
mejor_coste_teorico = 21

print('Número de actores: ',numero_actores)
print('Número de tomas: ', numero_tomas)
print('Máximo nº de tomas por día: ',max_tomas_por_dia)
print('Mejor coste teórico: ', mejor_coste_teorico)

Número de actores:  10
Número de tomas:  30
Máximo nº de tomas por día:  6
Mejor coste teórico:  21


## Solución básica

In [36]:
# Solución básica

# Función que calcula el coste total de la matriz solución
def calcula_coste(matriz_solucion):
  matriz_coste = np.zeros(10, dtype=int)
  # Recorremos la matriz solución y sumamos los días que a actuado un actor en una matriz de coste
  for dia in matriz_solucion:
    for act in range(len(dia)):
      # Si es mayor que 0 significa que ha actuado ese día y sumamos 1 a la posición correspondiente de la matriz de coste
      if dia[act] > 0:
        matriz_coste[act] += 1
  # Sumamos todos los valores de la matriz de coste para devolver el coste total
  return np.sum(matriz_coste)

def calcula_solucion(tomas, maximo_tomas):
  matriz_solucion = [np.zeros(10, dtype=int)]
  dia = 0
  n_tomas = 0

  for toma in tomas:
    # si el nº de tomas es mayor a 6 guardamos el día acutal y pasamos a un nuevo día en la matriz solución
    if (n_tomas >= maximo_tomas):
      n_tomas = 0
      dia += 1
      # Cargamos el nuevo día a cero en la matriz solución
      matriz_solucion = np.append(matriz_solucion, [np.zeros(10, dtype=int)], axis=0)

    # Sobre el día actual de la matriz solución sumamos una toma
    matriz_solucion[dia] = np.add(matriz_solucion[dia], toma)
    n_tomas +=1

  coste = calcula_coste(matriz_solucion)

  return coste, matriz_solucion


solucion = calcula_solucion(data, max_tomas_por_dia)
print('Coste: ', solucion[0])
print('Solución: \n', solucion[1])


Coste:  38
Solución: 
 [[3 5 2 4 4 0 2 2 0 0]
 [6 6 2 3 2 3 0 1 1 0]
 [4 1 3 2 1 2 1 0 0 1]
 [4 1 5 2 1 2 0 1 0 0]
 [5 1 1 4 3 1 0 0 1 1]]


El coste obtenido ha sido 38. Como vemos todavía está algo lejos de 21 que es el óptimo teórico. Vamo a ver que podemos hacer para mejorar esta solución.

### Solución por fuerza bruta
Para hayar la mejor solución por este método habría que explorar todas las soluciones posibles. Para ello "simplemente" bastaría con ejecutar el algoritmo anterior de solución básica tantas veces como posibilidades haya de distribuir las tomas (filas).<br>
Como ya se ha indicado, este problema tiene una complejidad factorial del orden de 30!. El coste computacional de este método es demasiado grande y disponemos de otros métodos que nos van a proporcionar, si no bien la mejor solución, soluciones óptimas en un tiempo mucho más reducido y manejable.

## Intercambio aleatorio de filas

Para este método lo que vamos a hacer generar una solución básica de la cuál obtendremos un coste. Tras eso vamos a intercambiar 2 filas de manera aleatoria y obtener de nuevo una solución. Esta segunda solución la vamos a comparar con la anterior, y en caso de tener un mejor coste que la anterior nos quedaremos con ella. Este proceso se repetirá tantas veces como se indique mediante el parámetro **intentos**

In [0]:
def intercambia_fila_aleatoria(data, intentos, mejor_coste, max_tomas_por_dia):
  # creamos una copia de los datos ya que con el intercambio de filas vamos a modificar la matriz constantemente y no queremos tocar la original
  copia_data = np.copy(data)
  for intento in range(intentos):
    # obtenemos una solución genérica
    solucion = calcula_solucion(copia_data, max_tomas_por_dia)
    # Si obtenemos una mejor solución la guardamos
    if (solucion[0] < mejor_coste):
      mejor_coste = solucion[0]
      mejor_matriz_solucion = solucion[1]
      print('coste: ', mejor_coste)
      print('solucion: \n', mejor_matriz_solucion)

      if mejor_coste == mejor_coste_teorico:
        return mejor_coste, mejor_matriz_solucion

    # generamos 2 número aleatorios entre 0 y 29 para intercambiar esas filas
    random = np.random.randint(low=0, high=30, size=2)
    t = np.copy(copia_data[random[0]])
    copia_data[random[0]] = copia_data[random[1]]
    copia_data[random[1]] = t

  return mejor_coste, mejor_matriz_solucion

# Definimos el nº de intentos
intentos = 10000
%time solucion = intercambia_fila_aleatoria(data, intentos, mejor_coste, max_tomas_por_dia)
print('\n\n')
print('Mejor coste: ', solucion[0])
print('Mejor solucion: \n', solucion[1])

coste:  38
solucion: 
 [[3 5 2 4 4 0 2 2 0 0]
 [6 6 2 3 2 3 0 1 1 0]
 [4 1 3 2 1 2 1 0 0 1]
 [4 1 5 2 1 2 0 1 0 0]
 [5 1 1 4 3 1 0 0 1 1]]
coste:  37
solucion: 
 [[3 5 2 4 4 0 2 2 0 0]
 [6 6 2 3 2 3 0 1 1 0]
 [4 2 3 3 1 1 1 0 0 1]
 [4 0 5 1 1 3 0 1 0 0]
 [5 1 1 4 3 1 0 0 1 1]]
coste:  36
solucion: 
 [[4 2 3 2 2 3 0 0 1 0]
 [5 3 2 5 4 0 1 0 0 0]
 [4 4 2 3 3 0 2 2 1 0]
 [5 2 3 3 2 1 0 1 0 1]
 [4 3 3 2 0 4 0 1 0 1]]
coste:  35
solucion: 
 [[5 3 2 3 0 2 1 2 0 0]
 [3 4 2 5 5 0 1 0 0 1]
 [4 0 3 4 3 1 0 0 0 0]
 [4 4 3 1 2 2 1 2 2 0]
 [6 3 3 2 1 3 0 0 0 1]]
coste:  34
solucion: 
 [[4 2 2 6 3 0 0 0 0 1]
 [6 2 2 4 2 2 0 0 0 1]
 [3 3 2 1 2 1 3 1 0 0]
 [5 2 4 0 1 4 0 0 2 0]
 [4 5 3 4 3 1 0 3 0 0]]
coste:  33
solucion: 
 [[4 4 0 4 2 0 2 1 0 2]
 [5 3 4 2 0 3 0 0 1 0]
 [5 3 3 1 2 3 0 2 0 0]
 [5 4 3 5 4 0 1 0 0 0]
 [3 0 3 3 3 2 0 1 1 0]]
coste:  31
solucion: 
 [[2 2 3 3 2 4 0 1 0 0]
 [5 2 4 4 2 0 0 0 0 0]
 [6 3 4 2 3 3 0 0 2 0]
 [4 4 2 0 2 1 3 3 0 0]
 [5 3 0 6 2 0 0 0 0 2]]
CPU times: user 1.46 s, sys

Podemos ver que con este método y ejecutanto unos **10000 intentos** hemos obtenido una solución de **coste 31** en apenas **1.46s** lo cual ya es un resultado decente.

En mis pruebas he lanzado este algoritmo varias veces con cientos de millones de intentos, los cuales requerían de entre 30 y 60 minutos de cálculo. El mínimo coste obtenido en todas esas ocasiones ha sido 30, por lo que creo que ese podría ser el límite para este método.

## Intercambiar filas a partir de la mejor solución

Para este algoritmo vamos a realizar una variante del método anterior. En este caso vamos obtener dos soluciones y nos vamos quedar con la que tenga un mejor coste de las dos. Una vez hecho esto volveremos a obtener otras dos soluciones a partir de esa mejor solución. <br>

De esta forma lo que se pretende es explorar múltiples opciones y trabajar trabajar a partir de la mejor. <br>

Para evitar posibles repeticiones e intentar acelerar el proceso, en la búsqueda de la primera solución se intercambiará solo una fila mientras que en la segunda se intercambiarán dos filas.



In [0]:
# función que intercambia una fila por otra
def intercambia_fila(matriz):
    random = np.random.randint(low=0, high=30, size=2)
    t = np.copy(matriz[random[0]])
    matriz[random[0]] = matriz[random[1]]
    matriz[random[1]] = t
    return matriz

# función que intercambia 2 filas aleatorias con otras 2
def intercambia_2_filas(matriz):
    random = np.random.randint(low=0, high=30, size=4)
    t = np.copy(matriz[random[0]])
    matriz[random[0]] = matriz[random[1]]
    matriz[random[1]] = t
    y = np.copy(matriz[random[2]])
    matriz[random[2]] = matriz[random[3]]
    matriz[random[3]] = y
    return matriz

def buscar_solucion(data, intentos, mejor_coste, max_tomas_por_dia):
  copia_data_1 = np.copy(data)
  copia_data_2 = np.copy(data)
  # hacemos 2 copias e intercambiamos una fila en la segunda
  copia_data_2 = intercambia_fila(copia_data_2)
  for intento in range(intentos):
    # cálculamos 2 soluciones
    solucion_1 = calcula_solucion(copia_data_1, max_tomas_por_dia)
    solucion_2 = calcula_solucion(copia_data_2, max_tomas_por_dia)

    # Nos quedamos con la matriz de la mejor solucion de las 2 
    if solucion_1[0] < solucion_2[0]:
      solucion = solucion_1
      copia_data_2 = copia_data_1
    else:
      solucion = solucion_2
      copia_data_1 = copia_data_2
  
    # Evaluamos si el coste la mejor solución es mejor que el que teníamos
    if (solucion[0] < mejor_coste):
      mejor_coste = solucion[0]
      mejor_matriz_solucion = solucion[1]
      print('coste: ', mejor_coste)
      print('solucion: \n', mejor_matriz_solucion)

      # comprobamos si hemos llegado al límite teórico
      if mejor_coste == mejor_coste_teorico:
        return mejor_coste, mejor_matriz_solucion

    # intercambiamos 1 y 2 filas
    copia_data_1 = intercambia_fila(copia_data_1)
    copia_data_2 = intercambia_2_filas(copia_data_2)
  
  return mejor_coste, mejor_matriz_solucion

intentos = 10000
%time solucion = buscar_solucion(data, intentos, mejor_coste, max_tomas_por_dia)
print('\n\n')
print('coste: ', solucion[0])
print('solucion: \n', solucion[1])

coste:  38
solucion: 
 [[3 5 2 4 4 0 2 2 0 0]
 [6 6 2 3 2 3 0 1 1 0]
 [4 1 3 2 1 2 1 0 0 1]
 [4 1 5 2 1 2 0 1 0 0]
 [5 1 1 4 3 1 0 0 1 1]]
coste:  36
solucion: 
 [[3 5 2 4 4 0 2 2 0 0]
 [6 5 3 2 2 3 0 1 2 0]
 [4 1 3 2 1 2 1 0 0 1]
 [4 0 4 2 1 2 0 1 0 0]
 [5 3 1 5 3 1 0 0 0 1]]
coste:  34
solucion: 
 [[4 2 4 4 3 2 0 0 0 0]
 [6 3 2 2 3 3 0 0 2 0]
 [5 4 3 1 2 1 3 1 0 0]
 [3 0 2 3 0 2 0 1 0 1]
 [4 5 2 5 3 0 0 2 0 1]]
coste:  33
solucion: 
 [[3 1 4 3 3 2 0 0 0 0]
 [6 2 3 1 3 4 0 0 2 0]
 [5 4 2 2 2 0 3 1 0 0]
 [5 3 2 5 0 1 0 0 0 2]
 [3 4 2 4 3 1 0 3 0 0]]
coste:  32
solucion: 
 [[4 0 3 5 3 0 0 0 0 0]
 [5 4 1 4 4 2 1 0 0 0]
 [4 3 3 0 1 2 2 3 0 0]
 [5 4 3 3 3 1 0 1 2 0]
 [4 3 3 3 0 3 0 0 0 2]]
CPU times: user 3.01 s, sys: 2.46 ms, total: 3.01 s
Wall time: 3.01 s



coste:  32
solucion: 
 [[4 0 3 5 3 0 0 0 0 0]
 [5 4 1 4 4 2 1 0 0 0]
 [4 3 3 0 1 2 2 3 0 0]
 [5 4 3 3 3 1 0 1 2 0]
 [4 3 3 3 0 3 0 0 0 2]]


Para el mismo número de intentos este algoritmo es algo más lento que el anterior. Este se explica fácilmente ya que en **cada intento tiene que buscar el doble de soluciones**.

En cuanto al resultado es parecido al anterior. Un coste de 32 en 3.01s.

Además, como ocurre en el algoritmo anterior, por mucho que aumentemos el número de intentos nunca se consigue bajar de coste 30.